spring:
  application:
    name: backend

  hospital:
    jdbc-url: jdbc:mysql://localhost:3306/Hospital?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:mysql://localhost:3306/Hospital?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.session.jdbc.initialize-schema=always
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect